/**
 */
package org.gemoc.sample.legacyfsm.fsm.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.gemoc.sample.legacyfsm.fsm.util.FsmAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class FsmItemProviderAdapterFactory extends FsmAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FsmItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.StateMachine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StateMachineItemProvider stateMachineItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.StateMachine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStateMachineAdapter() {
		if (stateMachineItemProvider == null) {
			stateMachineItemProvider = new StateMachineItemProvider(this);
		}

		return stateMachineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.State} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StateItemProvider stateItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.State}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStateAdapter() {
		if (stateItemProvider == null) {
			stateItemProvider = new StateItemProvider(this);
		}

		return stateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.Transition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransitionItemProvider transitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.Transition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransitionAdapter() {
		if (transitionItemProvider == null) {
			transitionItemProvider = new TransitionItemProvider(this);
		}

		return transitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.StringVariable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringVariableItemProvider stringVariableItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.StringVariable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringVariableAdapter() {
		if (stringVariableItemProvider == null) {
			stringVariableItemProvider = new StringVariableItemProvider(this);
		}

		return stringVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.NumberVariable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NumberVariableItemProvider numberVariableItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.NumberVariable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumberVariableAdapter() {
		if (numberVariableItemProvider == null) {
			numberVariableItemProvider = new NumberVariableItemProvider(this);
		}

		return numberVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.BooleanVariable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanVariableItemProvider booleanVariableItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.BooleanVariable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanVariableAdapter() {
		if (booleanVariableItemProvider == null) {
			booleanVariableItemProvider = new BooleanVariableItemProvider(this);
		}

		return booleanVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.BooleanGuard} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanGuardItemProvider booleanGuardItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.BooleanGuard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanGuardAdapter() {
		if (booleanGuardItemProvider == null) {
			booleanGuardItemProvider = new BooleanGuardItemProvider(this);
		}

		return booleanGuardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.StringGuard} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringGuardItemProvider stringGuardItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.StringGuard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringGuardAdapter() {
		if (stringGuardItemProvider == null) {
			stringGuardItemProvider = new StringGuardItemProvider(this);
		}

		return stringGuardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.EqualNumberGuard} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EqualNumberGuardItemProvider equalNumberGuardItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.EqualNumberGuard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEqualNumberGuardAdapter() {
		if (equalNumberGuardItemProvider == null) {
			equalNumberGuardItemProvider = new EqualNumberGuardItemProvider(this);
		}

		return equalNumberGuardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.StringAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringActionItemProvider stringActionItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.StringAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringActionAdapter() {
		if (stringActionItemProvider == null) {
			stringActionItemProvider = new StringActionItemProvider(this);
		}

		return stringActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.NumberAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NumberActionItemProvider numberActionItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.NumberAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumberActionAdapter() {
		if (numberActionItemProvider == null) {
			numberActionItemProvider = new NumberActionItemProvider(this);
		}

		return numberActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.BooleanAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanActionItemProvider booleanActionItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.BooleanAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanActionAdapter() {
		if (booleanActionItemProvider == null) {
			booleanActionItemProvider = new BooleanActionItemProvider(this);
		}

		return booleanActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.LessThanNumberGuard} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LessThanNumberGuardItemProvider lessThanNumberGuardItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.LessThanNumberGuard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLessThanNumberGuardAdapter() {
		if (lessThanNumberGuardItemProvider == null) {
			lessThanNumberGuardItemProvider = new LessThanNumberGuardItemProvider(this);
		}

		return lessThanNumberGuardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.GreaterThanNumberGuard} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GreaterThanNumberGuardItemProvider greaterThanNumberGuardItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.GreaterThanNumberGuard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGreaterThanNumberGuardAdapter() {
		if (greaterThanNumberGuardItemProvider == null) {
			greaterThanNumberGuardItemProvider = new GreaterThanNumberGuardItemProvider(this);
		}

		return greaterThanNumberGuardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.GreaterOrEqualThanNumberGuard} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GreaterOrEqualThanNumberGuardItemProvider greaterOrEqualThanNumberGuardItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.GreaterOrEqualThanNumberGuard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGreaterOrEqualThanNumberGuardAdapter() {
		if (greaterOrEqualThanNumberGuardItemProvider == null) {
			greaterOrEqualThanNumberGuardItemProvider = new GreaterOrEqualThanNumberGuardItemProvider(this);
		}

		return greaterOrEqualThanNumberGuardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.sample.legacyfsm.fsm.LessOrEqualThanNumberGuard} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LessOrEqualThanNumberGuardItemProvider lessOrEqualThanNumberGuardItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.sample.legacyfsm.fsm.LessOrEqualThanNumberGuard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLessOrEqualThanNumberGuardAdapter() {
		if (lessOrEqualThanNumberGuardItemProvider == null) {
			lessOrEqualThanNumberGuardItemProvider = new LessOrEqualThanNumberGuardItemProvider(this);
		}

		return lessOrEqualThanNumberGuardItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (stateMachineItemProvider != null) stateMachineItemProvider.dispose();
		if (stateItemProvider != null) stateItemProvider.dispose();
		if (transitionItemProvider != null) transitionItemProvider.dispose();
		if (stringVariableItemProvider != null) stringVariableItemProvider.dispose();
		if (numberVariableItemProvider != null) numberVariableItemProvider.dispose();
		if (booleanVariableItemProvider != null) booleanVariableItemProvider.dispose();
		if (booleanGuardItemProvider != null) booleanGuardItemProvider.dispose();
		if (stringGuardItemProvider != null) stringGuardItemProvider.dispose();
		if (equalNumberGuardItemProvider != null) equalNumberGuardItemProvider.dispose();
		if (stringActionItemProvider != null) stringActionItemProvider.dispose();
		if (numberActionItemProvider != null) numberActionItemProvider.dispose();
		if (booleanActionItemProvider != null) booleanActionItemProvider.dispose();
		if (lessThanNumberGuardItemProvider != null) lessThanNumberGuardItemProvider.dispose();
		if (greaterThanNumberGuardItemProvider != null) greaterThanNumberGuardItemProvider.dispose();
		if (greaterOrEqualThanNumberGuardItemProvider != null) greaterOrEqualThanNumberGuardItemProvider.dispose();
		if (lessOrEqualThanNumberGuardItemProvider != null) lessOrEqualThanNumberGuardItemProvider.dispose();
	}

}
