<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="montiarcTrace" nsURI="montiarcTrace" nsPrefix="montiarcTrace">
  <eClassifiers xsi:type="ecore:EClass" name="SpecificTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Montiarc_ComponentType_Compute_Sequence" upperBound="-1" eType="//Steps/Montiarc_ComponentType_Compute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Montiarc_ComponentType_Update_Sequence" upperBound="-1" eType="//Steps/Montiarc_ComponentType_Update"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="montiarc_tracedPortValues" ordered="false" upperBound="-1" eType="//States/montiarc/TracedPortValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="montiarc_tracedPorts" ordered="false" upperBound="-1" eType="//States/montiarc/TracedPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statesTrace" upperBound="-1" eType="//States/State" containment="true"/>
    <eGenericSuperTypes>
      <eTypeArguments>
        <eTypeArguments eClassifier="//Steps/SpecificStep"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SequentialStep"/>
      </eTypeArguments>
      <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Trace"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eSubpackages name="Steps" nsURI="montiarcTrace_Steps" nsPrefix="events">
    <eClassifiers xsi:type="ecore:EClass" name="Montiarc_ComponentType_Compute">
      <eOperations name="getCaller" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (ur1.diverse.montiarc.xdsml.xmontiarc.montiarc.ComponentType) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="../../ur1.diverse.montiarc.xdsml.xmontiarc/model/XMontiArc.ecore#/0/ComponentType"/>
      </eOperations>
      <eGenericSuperTypes eClassifier="//Steps/SpecificStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//Steps/Montiarc_ComponentType_Compute_AbstractSubStep"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SequentialStep"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="//Steps/Montiarc_ComponentType_Compute_AbstractSubStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Montiarc_ComponentType_Compute_AbstractSubStep" abstract="true" interface="true" eSuperTypes="//Steps/SpecificStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Montiarc_ComponentType_Compute_ImplicitStep">
      <eSuperTypes href="#//Steps/Montiarc_ComponentType_Compute_AbstractSubStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Montiarc_ComponentType_Update">
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (ur1.diverse.montiarc.xdsml.xmontiarc.montiarc.ComponentType) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="../../ur1.diverse.montiarc.xdsml.xmontiarc/model/XMontiArc.ecore#/0/ComponentType"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RootImplicitStep">
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificStep" abstract="true" interface="true">
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Step"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endingState" eType="//States/State" eOpposite="//States/State/endedSteps"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startingState" lowerBound="1" eType="//States/State" eOpposite="//States/State/startedSteps"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="States" nsURI="montiarcTrace_States" nsPrefix="tracedclasses">
    <eClassifiers xsi:type="ecore:EClass" name="Port_portValue_Value" eSuperTypes="//States/Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eOperations name="getStatesNoOpposite" lowerBound="1" upperBound="-1" eType="//States/State">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return this.getStates();"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1" eType="//States/montiarc/TracedPort" eOpposite="//States/montiarc/TracedPort/portValueSequence"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="portValue" unique="false" eType="//States/montiarc/TracedPortValue">
        <eAnnotations source="aspect"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1" upperBound="-1" eType="//States/State" eOpposite="//States/State/port_portValue_Values"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State">
      <eStructuralFeatures xsi:type="ecore:EReference" name="endedSteps" upperBound="-1" eType="//Steps/SpecificStep" eOpposite="//Steps/SpecificStep/endingState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="port_portValue_Values" ordered="false" upperBound="-1" eType="//States/Port_portValue_Value" eOpposite="//States/Port_portValue_Value/states"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startedSteps" upperBound="-1" eType="//Steps/SpecificStep" eOpposite="//Steps/SpecificStep/startingState"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statesNoOpposite" lowerBound="1" upperBound="-1" eType="//States/State" changeable="false" volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eSubpackages name="montiarc" nsURI="montiarcTrace_montiarc" nsPrefix="">
      <eClassifiers xsi:type="ecore:EClass" name="TracedPort">
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../ur1.diverse.montiarc.xdsml.xmontiarc/model/XMontiArc.ecore#/0/Port"/>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="portValueSequence" upperBound="-1" eType="//States/Port_portValue_Value" containment="true" eOpposite="//States/Port_portValue_Value/parent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedPortValue"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
