<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="montiarcruntime" nsURI="http://www.example.org/montiarcruntime" nsPrefix="montiarcruntime">
  <eClassifiers xsi:type="ecore:EClass" name="PortValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="../../ur1.diverse.cd.model/model/cd.ecore#//CDClass"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
