<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="fsm" nsURI="http://org.gemoc.xmontiarcfsm.xdsml.xmontiarcfsm/fsm/" nsPrefix="fsm">
    <eAnnotations source="http://www.eclipse.org/OCL/Import">
      <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="StateMachine" eSuperTypes="/0/NamedElement">
      <eOperations name="main">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="process">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="assignInitialValues">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedStates" upperBound="-1" eType="/0/State" containment="true" eOpposite="/0/State/owningFSM"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialState" lowerBound="1" eType="/0/State"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTransitions" upperBound="-1" eType="/0/Transition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1" eType="/0/Variable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="currentState" unique="false" eType="/0/State">
        <eAnnotations source="aspect"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningFSM" lowerBound="1" eType="/0/StateMachine" eOpposite="/0/StateMachine/ownedStates"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingTransitions" upperBound="-1" eType="/0/Transition" eOpposite="/0/Transition/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingTransitions" upperBound="-1" eType="/0/Transition" eOpposite="/0/Transition/target"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="/0/NamedElement">
      <eOperations name="execute">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="/0/State" eOpposite="/0/State/outgoingTransitions"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="/0/State" eOpposite="/0/State/incomingTransitions"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="input">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="output">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="guard" lowerBound="1" eType="/0/Guard" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1" eType="/0/Action" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" defaultValueLiteral="UnnamedVariable">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringVariable" eSuperTypes="/0/Variable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumberVariable" eSuperTypes="/0/Variable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanVariable" eSuperTypes="/0/Variable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Guard" abstract="true">
      <eOperations name="holds">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="not" defaultValueLiteral="false">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanGuard" eSuperTypes="/0/Guard">
      <eOperations name="holds">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" defaultValueLiteral="true">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="/0/BooleanVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringGuard" eSuperTypes="/0/Guard">
      <eOperations name="holds">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" defaultValueLiteral="UnnamedVariable">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="/0/StringVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumberGuard" abstract="true" eSuperTypes="/0/Guard">
      <eOperations name="holds">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" defaultValueLiteral="-1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="/0/NumberVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EqualNumberGuard" eSuperTypes="/0/NumberGuard">
      <eOperations name="holds">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
      <eOperations name="execute">
        <eAnnotations source="aspect"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringAction" eSuperTypes="/0/Action">
      <eOperations name="execute">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="/0/StringVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumberAction" eSuperTypes="/0/Action">
      <eOperations name="execute">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="/0/NumberVariable"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanAction" eSuperTypes="/0/Action">
      <eOperations name="execute">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="/0/BooleanVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LessThanNumberGuard" eSuperTypes="/0/NumberGuard">
      <eOperations name="holds">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GreaterThanNumberGuard" eSuperTypes="/0/NumberGuard">
      <eOperations name="holds">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GreaterOrEqualThanNumberGuard" eSuperTypes="/0/NumberGuard">
      <eOperations name="holds">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LessOrEqualThanNumberGuard" eSuperTypes="/0/NumberGuard">
      <eOperations name="holds">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eOperations>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="montiarc" nsURI="http://org.gemoc.xmontiarcfsm.xdsml.xmontiarcfsm/montiarc/" nsPrefix="montiarc">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="AtomicOrComposed"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="AtomicOrComposed" value="Tuple {&#xA;&#x9;message : String = 'Component type \'' + name + '\' cannot have connectors and behavior',&#xA;&#x9;status : Boolean = &#xA;            behavior.equalsIgnoreCase('') or self.connectors->isEmpty()&#xA;}.status"/>
      </eAnnotations>
      <eOperations name="initializeModel">
        <eAnnotations source="aspect"/>
        <eParameters name="args" upperBound="-1">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
      </eOperations>
      <eOperations name="main">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="compute">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="update">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="findOwnerOf" eType="/1/Subcomponent">
        <eAnnotations source="aspect"/>
        <eParameters name="p" eType="/1/Port"/>
      </eOperations>
      <eOperations name="getOutgoingPortsOfSubcomponents" upperBound="-1" eType="/1/Port">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="getIncomingPortsOfSubcomponents" upperBound="-1" eType="/1/Port">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="getDirectedPortsOfSubcomponents" upperBound="-1" eType="/1/Port">
        <eAnnotations source="aspect"/>
        <eParameters name="collectIncoming">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" defaultValueLiteral="UnnamedComponentType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1" eType="/1/Connector" containment="true" eOpposite="/1/Connector/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subcomponents" upperBound="-1" eType="/1/Subcomponent" containment="true" eOpposite="/1/Subcomponent/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingPorts" upperBound="-1" eType="/1/IncomingPort" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingPorts" upperBound="-1" eType="/1/OutgoingPort" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" eType="/1/ComponentBehavior"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Port">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="NameIsLowerCase"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="NameIsLowerCase" value="Tuple {&#xA;&#x9;message : String = 'Port \'' + name + '\' must be lowercase',&#xA;&#x9;status : Boolean = &#xA;            let firstLetter : String = (name).substring(0,1)&#xA;                in firstLetter.toLowerCase() = firstLetter&#xA;}.status"/>
      </eAnnotations>
      <eOperations name="toString">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="/1/DataType" defaultValueLiteral="Number"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" defaultValueLiteral="UnnamedPort">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="/1/EDataType">
        <eAnnotations source="aspect"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IncomingPort" eSuperTypes="/1/Port"/>
    <eClassifiers xsi:type="ecore:EClass" name="OutgoingPort" eSuperTypes="/1/Port">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" lowerBound="1" defaultValueLiteral="DefaultValue">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Connector" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="DifferentSourceAndTarget MatchingPortTypes"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="DifferentSourceAndTarget" value="Tuple {&#xA;&#x9;message : String = 'Connectors cannot have the same source and target.',&#xA;&#x9;status : Boolean = &#xA;            source &lt;> target&#xA;}.status"/>
        <details key="MatchingPortTypes" value="Tuple {&#xA;&#x9;message : String = 'The data types of source and target ports must match.',&#xA;&#x9;status : Boolean = &#xA;            source &lt;> target&#xA;}.status"/>
      </eAnnotations>
      <eOperations name="update">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="getSource" eType="/1/Port">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="getTarget" eType="/1/Port">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="getSourceRepresentation">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getTargetRepresentation">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getRepresentation">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="/1/ComponentType" eOpposite="/1/ComponentType/connectors"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntermediateConnector" eSuperTypes="/1/Connector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="/1/OutgoingPort"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="/1/IncomingPort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IncomingConnector" eSuperTypes="/1/Connector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="/1/IncomingPort"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="/1/IncomingPort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OutgoingConnector" eSuperTypes="/1/Connector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="/1/OutgoingPort"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="/1/OutgoingPort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Subcomponent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="NameIsLowerCase"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="NameIsLowerCase" value="Tuple {&#xA;&#x9;message : String = '\'' + name + '\' must be lowercase',&#xA;&#x9;status : Boolean = &#xA;            let firstLetter : String = (name).substring(0,1) &#xA;                in firstLetter.toLowerCase() = firstLetter&#xA;}.status"/>
      </eAnnotations>
      <eOperations name="createDefaultBehavior">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="compute">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" defaultValueLiteral="UnnamedSubcomponent">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="/1/ComponentType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingPorts" upperBound="-1" eType="/1/IncomingPort" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="/1/ComponentType" eOpposite="/1/ComponentType/subcomponents"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingPorts" upperBound="-1" eType="/1/OutgoingPort" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="localBehavior" eType="/1/ComponentBehavior" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DataType">
      <eLiterals name="Number" value="1" literal="Number"/>
      <eLiterals name="Boolean" literal="Boolean"/>
      <eLiterals name="String" value="2" literal="String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentBehavior" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="GroovyComponentBehavior" eSuperTypes="/1/ComponentBehavior">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scriptBody" lowerBound="1" defaultValueLiteral="&quot;&quot;">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AutomatonComponentBehavior" eSuperTypes="/1/ComponentBehavior">
      <eOperations name="wrapPortValuesToAutomaton">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="process">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="unwrapPortValuesFromAutomaton">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="delegateFSM" unique="false" eType="/1/StateMachine">
        <eAnnotations source="aspect"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EDataType" instanceClassName="org.eclipse.emf.ecore.EDataType">
      <eAnnotations source="aspect"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
      <eAnnotations source="aspect"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
